version: 0.1

phases:
  pre_build:
    commands:
    - npm install
    - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Sunit Kulkarni's Resume 2.26.2018.pdf
    - styles/*
    - images/*
    - dist/bundle.js