version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Sunit Kulkarni's Resume 2.26.2018.pdf
    - styles/*
    - images/*